name: CI

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '20 16 * * 6'

jobs:
  test:
    strategy:
      fail-fast: true
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install package dependencies
        run: sudo apt-get update -y && sudo apt-get install libgtk-4-dev gobject-introspection gir1.2-gtk-4.0 libgirepository1.0-dev
      - name: Install crystal dependencies
        run: shards install
      - name: Linter
        run: crystal tool format --check
      - name: Generate bindings
        run: ./bin/gi-crystal
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: crystal spec -v
